# fly.toml app configuration file generated for mobot on 2023-07-24T22:53:29+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mobot"
primary_region = "hkg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
